class GinoException(Exception): ...
class NoSuchRowError(GinoException): ...
class UninitializedError(GinoException): ...
class InitializedError(GinoException): ...
class UnknownJSONPropertyError(GinoException): ...
class MultipleResultsFound(GinoException): ...
class NoResultFound(GinoException): ...
