from typing import Any, Optional, Iterable, Mapping, Generator
from .engine import GinoConnection
from asyncpg.transaction import Transaction  # type: ignore

class _Break(BaseException):
    tx: GinoTransaction = ...
    commit: bool = ...
    def __init__(self, tx: GinoTransaction, commit: bool) -> None: ...

class GinoTransaction:
    def __init__(
        self, conn: GinoConnection, args: Iterable[Any], kwargs: Mapping[str, Any]
    ) -> None: ...
    @property
    def connection(self) -> GinoConnection: ...
    @property
    def raw_transaction(self) -> Transaction: ...
    def raise_commit(self) -> None: ...
    async def commit(self) -> None: ...
    def raise_rollback(self) -> None: ...
    async def rollback(self) -> None: ...
    def __await__(self) -> Generator[Any, None, GinoTransaction]: ...
    async def __aenter__(self) -> GinoTransaction: ...
    async def __aexit__(self, ex_type: Any, ex: Any, ex_tb: Any) -> Optional[bool]: ...
